# This file is part of the package itzbund/a11y-backend of the GSB 11 Project by ITZBund
# (c) Christian Rath-Ulrich <christian.rath-ulrich@digitaspixelpark.com> 2023
# It is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License, either version 2
# of the License, or any later version.
# For the full copyright and license information, please read the
# LICENSE file that was distributed with this source code.

services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  ITZBund\A11yBackend\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
