# SPDX-FileCopyrightText: 2024 Bundesrepublik Deutschland, vertreten durch das BMI/ITZBund
#
# SPDX-License-Identifier: GPL-3.0-or-later

services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  ITZBund\A11yBackend\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
